[package]
name = "slate"
version = "0.1.0"
edition = "2021"

[lib]
name = "slate_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "slate"
path = "src/main.rs"

[dependencies]
app-core = { path = "../crates/app-core" }
editor-core = { path = "../crates/editor-core" }
tauri = { version = "2", features = [] }
ulid = "1"
fend-core = "1"
regex = "1"
tauri-plugin-dialog = "2"
libc = "0.2"
arboard = "3.6.1"
base64 = "0.22"
time = { version = "0.3", features = ["formatting"] }
rustls = "0.23"
rustls-native-certs = "0.8"
mailparse = "0.15"
serde = { version = "1", features = ["derive"] }
[build-dependencies]
tauri-build = { version = "2", features = [] }
